# Generated by Django 2.2.7 on 2019-11-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(db_column='Trip_ID', primary_key=True, serialize=False)),
                ('trip_date', models.DateField(blank=True, db_column='Trip_Date', null=True)),
                ('route_id', models.IntegerField(blank=True, db_column='Route_ID', null=True)),
                ('trip_status', models.CharField(choices=[('cancelled', 'CANCELLED'), ('scheduled', 'SCHEDULED'), ('completed', 'COMPLETED')], db_column='Trip_Status', max_length=10)),
                ('truck_id', models.IntegerField(blank=True, db_column='Truck_ID', null=True)),
                ('truck_driver_id', models.IntegerField(blank=True, db_column='Truck_Driver_ID', null=True)),
            ],
            options={
                'db_table': 'trip',
                'managed': False,
            },
        ),
    ]
